import type { MetadataRoute } from "next";

/** Generated by Nexovix Connect */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/api/"],
    },
    host: "https://ringnest.games",
    sitemap: "https://ringnest.games/sitemap.xml",
  };
}
