import type { MetadataRoute } from "next";

/** Generated by Nexovix Connect — keep in sync with public/sitemap.xml */
export default function sitemap(): MetadataRoute.Sitemap {
  return [
  {
    url: "https://ringnest.games/",
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 1,
  },
  {
    url: "https://ringnest.games/games/pet-orbits",
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.8,
  },
  {
    url: "https://ringnest.games/catalog",
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.8,
  },
  {
    url: "https://ringnest.games/discord",
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.8,
  },
  {
    url: "https://ringnest.games/about",
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.8,
  },
  {
    url: "https://ringnest.games/games",
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.8,
  },
  {
    url: "https://ringnest.games/games/next-world",
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.8,
  }
  ];
}
