/* Generated by Nexovix Connect — loads GTM/GA + JSON-LD on no-CMS sites. */
import Script from "next/script";

const GTM_ID = process.env.NEXT_PUBLIC_GTM_ID || "GTM-TS9RR499";
const GA_ID = process.env.NEXT_PUBLIC_GA_ID || process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || "";

const JSON_LD = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "name": "Ringnest",
  "url": "https://ringnest.games/"
};

export function NexovixConnectTracking() {
  const gtmId = (GTM_ID || "").trim();
  const gaId = (GA_ID || "").trim();
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />
      {gtmId ? (
        <Script
          id="nexovix-gtm"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html:
              "(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','" +
              gtmId +
              "');",
          }}
        />
      ) : gaId ? (
        <>
          <Script
            src={"https://www.googletagmanager.com/gtag/js?id=" + gaId}
            strategy="afterInteractive"
          />
          <Script
            id="nexovix-ga4"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html:
                "window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','" +
                gaId +
                "');",
            }}
          />
        </>
      ) : null}
    </>
  );
}

export function NexovixConnectGtmNoscript() {
  const gtmId = (GTM_ID || "").trim();
  if (!gtmId) return null;
  return (
    <noscript>
      <iframe
        src={"https://www.googletagmanager.com/ns.html?id=" + gtmId}
        height="0"
        width="0"
        style={{ display: "none", visibility: "hidden" }}
      />
    </noscript>
  );
}
