/* Generated by Nexovix Connect — loads GTM/GA + JSON-LD on no-CMS sites. */
import Script from "next/script";

const GTM_ID = process.env.NEXT_PUBLIC_GTM_ID || "GTM-TS9RR499";
const GA_ID = process.env.NEXT_PUBLIC_GA_ID || process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || "";

const JSON_LD = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "name": "Ringnest",
  "url": "https://ringnest.games/"
};

export function NexovixConnectTracking() {
  const gtmId = (GTM_ID || "").trim();
  const gaId = (GA_ID || "").trim();
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />
      {gtmId ? (
        <Script
          id="nexovix-gtm"
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{
            __html:
              "(function(w,d,s,l,i){function boot(){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)}var done=false;function go(){if(done)return;done=true;boot()}var evts=['pointerdown','keydown','touchstart','scroll','click'];for(var e=0;e<evts.length;e++)w.addEventListener(evts[e],go,{once:true,capture:true,passive:true});w.setTimeout(go,45000)})(window,document,'script','dataLayer','" +
              gtmId +
              "');",
          }}
        />
      ) : gaId ? (
        <>
          <Script
            id="nexovix-ga4-src"
            strategy="lazyOnload"
            dangerouslySetInnerHTML={{
              __html:
                "(function(id){function boot(){var s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id='+id;document.head.appendChild(s);window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}window.gtag=gtag;gtag('js',new Date());gtag('config',id)}var done=false;function go(){if(done)return;done=true;boot()}var evts=['pointerdown','keydown','touchstart','scroll','click'];for(var e=0;e<evts.length;e++)window.addEventListener(evts[e],go,{once:true,capture:true,passive:true});setTimeout(go,45000)})('" +
                gaId +
                "');",
            }}
          />
        </>
      ) : null}
    </>
  );
}

export function NexovixConnectGtmNoscript() {
  const gtmId = (GTM_ID || "").trim();
  if (!gtmId) return null;
  return (
    <noscript>
      <iframe
        src={"https://www.googletagmanager.com/ns.html?id=" + gtmId}
        height="0"
        width="0"
        style={{ display: "none", visibility: "hidden" }}
      />
    </noscript>
  );
}
