/* Generated by Nexovix Connect — PageSpeed preconnect / resource hints. */
export function NexovixPerfHints() {
  return (
    <>
      <link rel="preconnect" href="https://www.googletagmanager.com" crossOrigin="anonymous" />
      <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
      <link rel="dns-prefetch" href="https://www.google-analytics.com" />
      <link rel="dns-prefetch" href="https://www.clarity.ms" />
    </>
  );
}
