/* Generated by Nexovix Connect — PageSpeed pack 2 (hints + third-party gate). */
import Script from "next/script";

export function NexovixPerfHints() {
  return (
    <>
      <Script
        id="nexovix-perf-v2-gate"
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{
          __html: "(function(){try{var R=/virtuagym\\.com|connect\\.facebook\\.net|fbevents|googletagmanager\\.com\\/gtm\\.js|googletagmanager\\.com\\/gtag|google-analytics\\.com|clarity\\.ms|hotjar\\.com/i;var q=[];var go=false;function flush(){if(go)return;go=true;var jobs=q.splice(0);function step(i){if(i>=jobs.length)return;try{jobs[i]()}catch(e){}setTimeout(function(){step(i+1)},40)}step(0)}function arm(){var run=function(){if(window.requestIdleCallback)requestIdleCallback(flush,{timeout:2000});else setTimeout(flush,1200)};if(document.readyState===\"complete\")run();else window.addEventListener(\"load\",run,{once:true});setTimeout(flush,6000)}function heavy(node){if(!node||node.nodeType!==1)return false;var tag=node.tagName;if(tag===\"SCRIPT\"){var src=node.src||node.getAttribute(\"src\")||\"\";return !!(src&&R.test(src))}if(tag===\"LINK\"){var href=node.href||node.getAttribute(\"href\")||\"\";var rel=(node.rel||node.getAttribute(\"rel\")||\"\").toLowerCase();if(!href||!R.test(href))return false;return rel===\"stylesheet\"||rel===\"preload\"||rel===\"prefetch\"}return false}function wrap(proto,method){var orig=proto[method];if(!orig||orig.__nexovixPerf)return;function wrapped(node){if(!go&&heavy(node)){var self=this,args=arguments;q.push(function(){orig.apply(self,args)});return node}return orig.apply(this,arguments)}wrapped.__nexovixPerf=1;proto[method]=wrapped}wrap(Node.prototype,\"appendChild\");wrap(Node.prototype,\"insertBefore\");arm()}catch(e){}})();",
        }}
      />
      <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
      <link rel="dns-prefetch" href="https://www.google-analytics.com" />
      <link rel="dns-prefetch" href="https://www.clarity.ms" />
    </>
  );
}
