export type PetRarity = "Common" | "Uncommon" | "Rare" | "Epic" | "Legendary" | "Limited" | "Apex";
export type PetBiome =
	| "Arena"
	| "Meadow"
	| "Lake"
	| "Crystal"
	| "Desert"
	| "Jungle"
	| "Ember"
	| "Snow"
	| "Frost"
	| "Volcano"
	| "Abyss"
	| "Cosmic"
	| "Celestial"
	| "Limited"
	| "Prime";

export type CatalogPet = {
	id: string;
	name: string;
	rarity: PetRarity;
	biome: PetBiome;
	income: number;
	color: string;
	hint: string;
};

export const RARITY_ORDER: PetRarity[] = [
	"Common",
	"Uncommon",
	"Rare",
	"Epic",
	"Legendary",
	"Limited",
	"Apex",
];

export const BIOME_ORDER: PetBiome[] = [
	"Arena",
	"Meadow",
	"Lake",
	"Crystal",
	"Desert",
	"Jungle",
	"Ember",
	"Snow",
	"Frost",
	"Volcano",
	"Abyss",
	"Cosmic",
	"Celestial",
	"Limited",
	"Prime",
];

export const RARITY_COLORS: Record<PetRarity, string> = {
	Common: "#b4b4b4",
	Uncommon: "#50c878",
	Rare: "#468cff",
	Epic: "#b450ff",
	Legendary: "#ffc84a",
	Limited: "#ff46dc",
	Apex: "#ffe678",
};

export const pets: CatalogPet[] = [
	{ id: "OrbitPup", name: "Orbit Pup", rarity: "Common", biome: "Arena", income: 1, color: "#b4b4b4", hint: "Starter pen pet" },
	{ id: "RingKit", name: "Ring Kit", rarity: "Uncommon", biome: "Arena", income: 3, color: "#50c878", hint: "Quick earner" },
	{ id: "PlazaCat", name: "Plaza Cat", rarity: "Rare", biome: "Arena", income: 8, color: "#dcb45a", hint: "Stadium mascot" },
	{ id: "RingHound", name: "Ring Hound", rarity: "Epic", biome: "Arena", income: 20, color: "#5a5a6e", hint: "Crash specialist" },
	{ id: "MeadowPup", name: "Meadow Pup", rarity: "Common", biome: "Meadow", income: 1, color: "#5abe64", hint: "Soft grass" },
	{ id: "CloverMouse", name: "Clover Mouse", rarity: "Common", biome: "Meadow", income: 1, color: "#8cd25a", hint: "Lucky nibble" },
	{ id: "LeafLynx", name: "Leaf Lynx", rarity: "Uncommon", biome: "Meadow", income: 4, color: "#78dc5a", hint: "Forest prowler" },
	{ id: "HoneyBee", name: "Honey Bee", rarity: "Uncommon", biome: "Meadow", income: 4, color: "#ffc828", hint: "Sweet coins" },
	{ id: "BloomBear", name: "Bloom Bear", rarity: "Rare", biome: "Meadow", income: 9, color: "#a0ff78", hint: "Meadow tank" },
	{ id: "ThistleFox", name: "Thistle Fox", rarity: "Rare", biome: "Meadow", income: 10, color: "#5aa046", hint: "Bramble dash" },
	{ id: "GroveKing", name: "Grove King", rarity: "Epic", biome: "Meadow", income: 22, color: "#3ca046", hint: "Meadow apex" },
	{ id: "PuddleFrog", name: "Puddle Frog", rarity: "Common", biome: "Lake", income: 2, color: "#46b45a", hint: "Shore hopper" },
	{ id: "TideCrab", name: "Tide Crab", rarity: "Common", biome: "Lake", income: 2, color: "#c85a46", hint: "Sideways steal" },
	{ id: "ReedOtter", name: "Reed Otter", rarity: "Uncommon", biome: "Lake", income: 5, color: "#5aa0c8", hint: "River dash" },
	{ id: "CoralSeal", name: "Coral Seal", rarity: "Uncommon", biome: "Lake", income: 5, color: "#f0a0aa", hint: "Splash orbit" },
	{ id: "LakeSwan", name: "Lake Swan", rarity: "Rare", biome: "Lake", income: 11, color: "#e6f0ff", hint: "Grace steal" },
	{ id: "LeviCub", name: "Levi Cub", rarity: "Legendary", biome: "Lake", income: 52, color: "#285ab4", hint: "Lake legend" },
	{ id: "RiverDrake", name: "River Drake", rarity: "Epic", biome: "Lake", income: 24, color: "#288cc8", hint: "Current king" },
	{ id: "ShardCub", name: "Shard Cub", rarity: "Common", biome: "Crystal", income: 2, color: "#8cc8ff", hint: "Tiny crystal" },
	{ id: "QuartzBat", name: "Quartz Bat", rarity: "Common", biome: "Crystal", income: 2, color: "#c8dcff", hint: "Cave glitter" },
	{ id: "PrismFox", name: "Prism Fox", rarity: "Uncommon", biome: "Crystal", income: 6, color: "#64b4ff", hint: "Glint runner" },
	{ id: "OpalMoth", name: "Opal Moth", rarity: "Uncommon", biome: "Crystal", income: 6, color: "#ffb4dc", hint: "Gem wing" },
	{ id: "GeoWolf", name: "Geo Wolf", rarity: "Rare", biome: "Crystal", income: 12, color: "#508cff", hint: "Crystal pack" },
	{ id: "DiamondDrake", name: "Diamond Drake", rarity: "Legendary", biome: "Crystal", income: 58, color: "#c8f0ff", hint: "Crystal legend" },
	{ id: "GeodeOwl", name: "Geode Owl", rarity: "Epic", biome: "Crystal", income: 25, color: "#a078ff", hint: "Night facet" },
	{ id: "SandPup", name: "Sand Pup", rarity: "Common", biome: "Desert", income: 2, color: "#e6be5a", hint: "Dune pup" },
	{ id: "CactusHare", name: "Cactus Hare", rarity: "Common", biome: "Desert", income: 2, color: "#78b446", hint: "Spike hop" },
	{ id: "DuneFox", name: "Dune Fox", rarity: "Uncommon", biome: "Desert", income: 6, color: "#d2963c", hint: "Heat dash" },
	{ id: "ScarabDrone", name: "Scarab Drone", rarity: "Uncommon", biome: "Desert", income: 6, color: "#285032", hint: "Tomb buzz" },
	{ id: "SphinxCat", name: "Sphinx Cat", rarity: "Epic", biome: "Desert", income: 24, color: "#ffd278", hint: "Temple cat" },
	{ id: "SolarSerpent", name: "Solar Serpent", rarity: "Legendary", biome: "Desert", income: 62, color: "#ffaa28", hint: "Desert legend" },
	{ id: "OasisLynx", name: "Oasis Lynx", rarity: "Rare", biome: "Desert", income: 13, color: "#50b48c", hint: "Cool sand" },
	{ id: "CanopyBird", name: "Canopy Bird", rarity: "Common", biome: "Jungle", income: 2, color: "#50c846", hint: "Tree dart" },
	{ id: "PoisonFrog", name: "Poison Frog", rarity: "Common", biome: "Jungle", income: 2, color: "#50ff28", hint: "Bright hop" },
	{ id: "VineCat", name: "Vine Cat", rarity: "Uncommon", biome: "Jungle", income: 7, color: "#32a046", hint: "Silent drop" },
	{ id: "SlothOrb", name: "Sloth Orb", rarity: "Uncommon", biome: "Jungle", income: 6, color: "#a08250", hint: "Slow coins" },
	{ id: "JadeGorilla", name: "Jade Gorilla", rarity: "Rare", biome: "Jungle", income: 14, color: "#288c3c", hint: "Canopy king" },
	{ id: "TigerBloom", name: "Tiger Bloom", rarity: "Legendary", biome: "Jungle", income: 70, color: "#ff8c28", hint: "Jungle legend" },
	{ id: "OrchidPanther", name: "Orchid Panther", rarity: "Epic", biome: "Jungle", income: 27, color: "#b43c8c", hint: "Night bloom" },
	{ id: "CinderPup", name: "Cinder Pup", rarity: "Common", biome: "Ember", income: 2, color: "#ff8c46", hint: "Warm sand" },
	{ id: "SparkLizard", name: "Spark Lizard", rarity: "Common", biome: "Ember", income: 2, color: "#ff5a28", hint: "Hot stone" },
	{ id: "EmberMoth", name: "Ember Moth", rarity: "Uncommon", biome: "Ember", income: 7, color: "#ffa050", hint: "Ash wing" },
	{ id: "AshFox", name: "Ash Fox", rarity: "Rare", biome: "Ember", income: 13, color: "#ff6432", hint: "Ember stalker" },
	{ id: "MagmaBull", name: "Magma Bull", rarity: "Epic", biome: "Ember", income: 26, color: "#ff5028", hint: "Molten charge" },
	{ id: "PhoenixOrb", name: "Phoenix Orb", rarity: "Legendary", biome: "Ember", income: 75, color: "#ffb43c", hint: "Ember legend" },
	{ id: "CoalRam", name: "Coal Ram", rarity: "Rare", biome: "Ember", income: 14, color: "#3c2828", hint: "Soot charge" },
	{ id: "SnowKit", name: "Snow Kit", rarity: "Common", biome: "Snow", income: 2, color: "#e6f5ff", hint: "Powder pup" },
	{ id: "PolarCub", name: "Polar Cub", rarity: "Common", biome: "Snow", income: 2, color: "#f0faff", hint: "White fluff" },
	{ id: "PuffinOrb", name: "Puffin Orb", rarity: "Uncommon", biome: "Snow", income: 7, color: "#282832", hint: "Icy flyer" },
	{ id: "IceHare", name: "Ice Hare", rarity: "Uncommon", biome: "Snow", income: 7, color: "#c8e6ff", hint: "Powder hop" },
	{ id: "YetiCub", name: "Yeti Cub", rarity: "Epic", biome: "Snow", income: 28, color: "#c8dcf0", hint: "Snow titan" },
	{ id: "GlacierWyrm", name: "Glacier Wyrm", rarity: "Legendary", biome: "Snow", income: 80, color: "#b4f0ff", hint: "Snow legend" },
	{ id: "FrostSeal", name: "Frost Seal", rarity: "Rare", biome: "Snow", income: 15, color: "#a0c8e6", hint: "Ice slide" },
	{ id: "HailWisp", name: "Hail Wisp", rarity: "Common", biome: "Frost", income: 3, color: "#c8e6ff", hint: "Cold spark" },
	{ id: "IceOwl", name: "Ice Owl", rarity: "Uncommon", biome: "Frost", income: 8, color: "#b4dcff", hint: "Frost watcher" },
	{ id: "SnowLeopard", name: "Snow Leopard", rarity: "Rare", biome: "Frost", income: 16, color: "#dce6f0", hint: "Silent ice" },
	{ id: "CrystalStag", name: "Crystal Stag", rarity: "Rare", biome: "Frost", income: 16, color: "#c8f0ff", hint: "Aurora run" },
	{ id: "FrostMammoth", name: "Frost Mammoth", rarity: "Epic", biome: "Frost", income: 30, color: "#a0c8ff", hint: "Frost titan" },
	{ id: "AuroraDrake", name: "Aurora Drake", rarity: "Legendary", biome: "Frost", income: 85, color: "#8cffe6", hint: "Frost legend" },
	{ id: "RimeWolf", name: "Rime Wolf", rarity: "Epic", biome: "Frost", income: 31, color: "#8cb4dc", hint: "Pack ice" },
	{ id: "FireSlug", name: "Fire Slug", rarity: "Common", biome: "Volcano", income: 3, color: "#ff501e", hint: "Slow melt" },
	{ id: "AshBat", name: "Ash Bat", rarity: "Uncommon", biome: "Volcano", income: 9, color: "#501e14", hint: "Smoke wing" },
	{ id: "LavaGecko", name: "Lava Gecko", rarity: "Rare", biome: "Volcano", income: 18, color: "#ff5a28", hint: "Hot stone" },
	{ id: "EmberCrab", name: "Ember Crab", rarity: "Rare", biome: "Volcano", income: 17, color: "#c83c1e", hint: "Crust snap" },
	{ id: "CinderHound", name: "Cinder Hound", rarity: "Epic", biome: "Volcano", income: 34, color: "#c8321e", hint: "Ash chase" },
	{ id: "ObsidianOx", name: "Obsidian Ox", rarity: "Epic", biome: "Volcano", income: 32, color: "#281414", hint: "Black rock" },
	{ id: "MagmaDrake", name: "Magma Drake", rarity: "Legendary", biome: "Volcano", income: 95, color: "#ff4614", hint: "Volcano legend" },
	{ id: "TideJelly", name: "Tide Jelly", rarity: "Common", biome: "Abyss", income: 3, color: "#50c8dc", hint: "Glow pulse" },
	{ id: "DeepCrab", name: "Deep Crab", rarity: "Uncommon", biome: "Abyss", income: 9, color: "#28508c", hint: "Pressure pinch" },
	{ id: "PearlRay", name: "Pearl Ray", rarity: "Uncommon", biome: "Abyss", income: 10, color: "#b4dcff", hint: "Tide glide" },
	{ id: "GlowEel", name: "Glow Eel", rarity: "Rare", biome: "Abyss", income: 20, color: "#28b4ff", hint: "Deep flash" },
	{ id: "AnglerPup", name: "Angler Pup", rarity: "Rare", biome: "Abyss", income: 19, color: "#1e5a46", hint: "Lure bite" },
	{ id: "AbyssShark", name: "Abyss Shark", rarity: "Epic", biome: "Abyss", income: 36, color: "#1e3c78", hint: "Dark bite" },
	{ id: "KrakenOrb", name: "Kraken Orb", rarity: "Legendary", biome: "Abyss", income: 110, color: "#1450a0", hint: "Abyss legend" },
	{ id: "CometPup", name: "Comet Pup", rarity: "Common", biome: "Cosmic", income: 4, color: "#c8b4ff", hint: "Streak orbit" },
	{ id: "MoonHare", name: "Moon Hare", rarity: "Uncommon", biome: "Cosmic", income: 12, color: "#e6e6ff", hint: "Lunar hop" },
	{ id: "VoidMoth", name: "Void Moth", rarity: "Uncommon", biome: "Cosmic", income: 11, color: "#50288c", hint: "Dark wing" },
	{ id: "StarMite", name: "Star Mite", rarity: "Rare", biome: "Cosmic", income: 22, color: "#b48cff", hint: "Orbit dust" },
	{ id: "OrbitOwl", name: "Orbit Owl", rarity: "Rare", biome: "Cosmic", income: 21, color: "#6450b4", hint: "Night watch" },
	{ id: "NebulaCat", name: "Nebula Cat", rarity: "Epic", biome: "Cosmic", income: 40, color: "#8c50dc", hint: "Void purr" },
	{ id: "CosmicWyrm", name: "Cosmic Wyrm", rarity: "Legendary", biome: "Cosmic", income: 130, color: "#783cff", hint: "Cosmic legend" },
	{ id: "CloudLamb", name: "Cloud Lamb", rarity: "Uncommon", biome: "Celestial", income: 14, color: "#fffaf0", hint: "Soft sky" },
	{ id: "DawnStag", name: "Dawn Stag", rarity: "Rare", biome: "Celestial", income: 24, color: "#ffe6a0", hint: "First light" },
	{ id: "HaloDove", name: "Halo Dove", rarity: "Epic", biome: "Celestial", income: 44, color: "#fff0b4", hint: "Light wing" },
	{ id: "StarUnicorn", name: "Star Unicorn", rarity: "Epic", biome: "Celestial", income: 46, color: "#fff5c8", hint: "Horn gleam" },
	{ id: "SeraphFox", name: "Seraph Fox", rarity: "Legendary", biome: "Celestial", income: 150, color: "#ffdc78", hint: "Celestial legend" },
	{ id: "AetherLion", name: "Aether Lion", rarity: "Legendary", biome: "Celestial", income: 160, color: "#ffc850", hint: "Sky king" },
	{ id: "GoldPhoenix", name: "Gold Phoenix", rarity: "Legendary", biome: "Celestial", income: 175, color: "#ffd246", hint: "Sun rebirth" },
	{ id: "CoinMoth", name: "Coin Moth", rarity: "Common", biome: "Arena", income: 2, color: "#dcc850", hint: "Plaza dust" },
	{ id: "TrophyPup", name: "Trophy Pup", rarity: "Rare", biome: "Arena", income: 9, color: "#ffd25a", hint: "Winner's orb" },
	{ id: "GrassHopper", name: "Grass Hopper", rarity: "Common", biome: "Meadow", income: 2, color: "#6ec846", hint: "Jump coins" },
	{ id: "DaisyDuck", name: "Daisy Duck", rarity: "Uncommon", biome: "Meadow", income: 5, color: "#ffe650", hint: "Pond waddle" },
	{ id: "FernBoar", name: "Fern Boar", rarity: "Rare", biome: "Meadow", income: 11, color: "#5a8c3c", hint: "Root charge" },
	{ id: "WillowStag", name: "Willow Stag", rarity: "Epic", biome: "Meadow", income: 23, color: "#8cb45a", hint: "Shade run" },
	{ id: "MossDragon", name: "Moss Dragon", rarity: "Legendary", biome: "Meadow", income: 48, color: "#32823c", hint: "Meadow legend" },
	{ id: "LilyPad", name: "Lily Pad", rarity: "Common", biome: "Lake", income: 2, color: "#50c86e", hint: "Float steal" },
	{ id: "MinnowOrb", name: "Minnow Orb", rarity: "Uncommon", biome: "Lake", income: 6, color: "#64b4dc", hint: "School dash" },
	{ id: "HeronOrb", name: "Heron Orb", rarity: "Rare", biome: "Lake", income: 12, color: "#c8dcf0", hint: "Still hunt" },
	{ id: "TideTurtle", name: "Tide Turtle", rarity: "Epic", biome: "Lake", income: 25, color: "#3c8c5a", hint: "Shell bank" },
	{ id: "StormPike", name: "Storm Pike", rarity: "Legendary", biome: "Lake", income: 55, color: "#1e50a0", hint: "Lake apex" },
	{ id: "PebbleCrab", name: "Pebble Crab", rarity: "Common", biome: "Crystal", income: 2, color: "#b4d2e6", hint: "Click coins" },
	{ id: "IceBeetle", name: "Ice Beetle", rarity: "Uncommon", biome: "Crystal", income: 6, color: "#a0c8ff", hint: "Facet walk" },
	{ id: "SapphireCat", name: "Sapphire Cat", rarity: "Rare", biome: "Crystal", income: 13, color: "#285adc", hint: "Blue purr" },
	{ id: "PrismElk", name: "Prism Elk", rarity: "Epic", biome: "Crystal", income: 26, color: "#b4dcff", hint: "Light antler" },
	{ id: "CrownGolem", name: "Crown Golem", rarity: "Legendary", biome: "Crystal", income: 64, color: "#dcf0ff", hint: "Crystal king" },
	{ id: "DustMouse", name: "Dust Mouse", rarity: "Common", biome: "Desert", income: 2, color: "#d2b478", hint: "Sand nibble" },
	{ id: "MirageFox", name: "Mirage Fox", rarity: "Uncommon", biome: "Desert", income: 7, color: "#ffc864", hint: "Heat ghost" },
	{ id: "CamelCub", name: "Camel Cub", rarity: "Rare", biome: "Desert", income: 14, color: "#c8a05a", hint: "Long walk" },
	{ id: "AnubisHound", name: "Anubis Hound", rarity: "Epic", biome: "Desert", income: 28, color: "#281e32", hint: "Tomb guard" },
	{ id: "SunSphinx", name: "Sun Sphinx", rarity: "Legendary", biome: "Desert", income: 68, color: "#ffb432", hint: "Desert king" },
	{ id: "SeedBat", name: "Seed Bat", rarity: "Common", biome: "Jungle", income: 2, color: "#3c6432", hint: "Fruit drop" },
	{ id: "ToucanOrb", name: "Toucan Orb", rarity: "Uncommon", biome: "Jungle", income: 7, color: "#ff5028", hint: "Beak flash" },
	{ id: "PythonOrb", name: "Python Orb", rarity: "Rare", biome: "Jungle", income: 15, color: "#327832", hint: "Coil steal" },
	{ id: "LotusTiger", name: "Lotus Tiger", rarity: "Epic", biome: "Jungle", income: 29, color: "#ff7850", hint: "Bloom hunt" },
	{ id: "CanopyWyrm", name: "Canopy Wyrm", rarity: "Legendary", biome: "Jungle", income: 78, color: "#28a032", hint: "Jungle king" },
	{ id: "SparkBug", name: "Spark Bug", rarity: "Common", biome: "Ember", income: 3, color: "#ffa028", hint: "Hot flicker" },
	{ id: "SootCat", name: "Soot Cat", rarity: "Uncommon", biome: "Ember", income: 8, color: "#503228", hint: "Ash nap" },
	{ id: "KilnRam", name: "Kiln Ram", rarity: "Rare", biome: "Ember", income: 15, color: "#b44628", hint: "Fired charge" },
	{ id: "LavaOtter", name: "Lava Otter", rarity: "Epic", biome: "Ember", income: 30, color: "#ff5a28", hint: "Molten slide" },
	{ id: "AshPhoenix", name: "Ash Phoenix", rarity: "Legendary", biome: "Ember", income: 82, color: "#ff7832", hint: "Ember king" },
	{ id: "FlakePup", name: "Flake Pup", rarity: "Common", biome: "Snow", income: 3, color: "#f0faff", hint: "Soft snow" },
	{ id: "SkiFox", name: "Ski Fox", rarity: "Uncommon", biome: "Snow", income: 8, color: "#dce6fa", hint: "Slope dash" },
	{ id: "IglooBear", name: "Igloo Bear", rarity: "Rare", biome: "Snow", income: 16, color: "#e6f0ff", hint: "Den tank" },
	{ id: "BlizzardOwl", name: "Blizzard Owl", rarity: "Epic", biome: "Snow", income: 32, color: "#c8dcff", hint: "White wing" },
	{ id: "NorthWyrm", name: "North Wyrm", rarity: "Legendary", biome: "Snow", income: 88, color: "#b4e6ff", hint: "Snow king" },
	{ id: "FrostMite", name: "Frost Mite", rarity: "Common", biome: "Frost", income: 3, color: "#bedcff", hint: "Ice speck" },
	{ id: "HailFox", name: "Hail Fox", rarity: "Uncommon", biome: "Frost", income: 9, color: "#aad2ff", hint: "Pelt ice" },
	{ id: "RimeBear", name: "Rime Bear", rarity: "Rare", biome: "Frost", income: 17, color: "#96c8f0", hint: "Frozen tank" },
	{ id: "AuroraCat", name: "Aurora Cat", rarity: "Epic", biome: "Frost", income: 33, color: "#78ffd2", hint: "Sky purr" },
	{ id: "IceTitan", name: "Ice Titan", rarity: "Legendary", biome: "Frost", income: 92, color: "#a0dcff", hint: "Frost king" },
	{ id: "CinderAnt", name: "Cinder Ant", rarity: "Common", biome: "Volcano", income: 3, color: "#c83c1e", hint: "Hot trail" },
	{ id: "SmokeWeasel", name: "Smoke Weasel", rarity: "Uncommon", biome: "Volcano", income: 10, color: "#5a281e", hint: "Ash dash" },
	{ id: "BasaltBoar", name: "Basalt Boar", rarity: "Rare", biome: "Volcano", income: 18, color: "#3c1e19", hint: "Rock charge" },
	{ id: "PyroHawk", name: "Pyro Hawk", rarity: "Epic", biome: "Volcano", income: 35, color: "#ff501e", hint: "Heat dive" },
	{ id: "VolcanoKing", name: "Volcano King", rarity: "Legendary", biome: "Volcano", income: 105, color: "#ff3214", hint: "Crater apex" },
	{ id: "BubbleFish", name: "Bubble Fish", rarity: "Common", biome: "Abyss", income: 3, color: "#46a0c8", hint: "Pop coins" },
	{ id: "InkSquid", name: "Ink Squid", rarity: "Uncommon", biome: "Abyss", income: 10, color: "#281e50", hint: "Dark cloud" },
	{ id: "CoralHound", name: "Coral Hound", rarity: "Rare", biome: "Abyss", income: 19, color: "#ff788c", hint: "Reef bite" },
	{ id: "LeviathanCub", name: "Leviathan Cub", rarity: "Epic", biome: "Abyss", income: 38, color: "#143264", hint: "Deep king" },
	{ id: "AbyssTitan", name: "Abyss Titan", rarity: "Legendary", biome: "Abyss", income: 120, color: "#0a285a", hint: "Trench apex" },
	{ id: "DustStar", name: "Dust Star", rarity: "Common", biome: "Cosmic", income: 4, color: "#c8b4ff", hint: "Orbit spec" },
	{ id: "PulsarBat", name: "Pulsar Bat", rarity: "Uncommon", biome: "Cosmic", income: 12, color: "#a050ff", hint: "Pulse wing" },
	{ id: "QuasarFox", name: "Quasar Fox", rarity: "Rare", biome: "Cosmic", income: 22, color: "#643cc8", hint: "Bright dash" },
	{ id: "VoidElk", name: "Void Elk", rarity: "Epic", biome: "Cosmic", income: 42, color: "#3c1e78", hint: "Dark antler" },
	{ id: "GalaxyWyrm", name: "Galaxy Wyrm", rarity: "Legendary", biome: "Cosmic", income: 140, color: "#5028c8", hint: "Cosmic king" },
	{ id: "SunMoth", name: "Sun Moth", rarity: "Common", biome: "Celestial", income: 5, color: "#fff0a0", hint: "Warm wing" },
	{ id: "HaloKit", name: "Halo Kit", rarity: "Uncommon", biome: "Celestial", income: 14, color: "#fff5c8", hint: "Ring pup" },
	{ id: "CloudTiger", name: "Cloud Tiger", rarity: "Rare", biome: "Celestial", income: 26, color: "#fffaf0", hint: "Sky hunt" },
	{ id: "DawnWyrm", name: "Dawn Wyrm", rarity: "Epic", biome: "Celestial", income: 48, color: "#ffdc8c", hint: "Morning coil" },
	{ id: "HeavenKing", name: "Heaven King", rarity: "Legendary", biome: "Celestial", income: 190, color: "#ffe664", hint: "Celestial apex" },
	{ id: "TitanRing", name: "Titan Ring", rarity: "Limited", biome: "Limited", income: 220, color: "#ff46dc", hint: "Weekly limited" },
	{ id: "VoidColossus", name: "Void Colossus", rarity: "Limited", biome: "Limited", income: 240, color: "#5028a0", hint: "Weekly limited" },
	{ id: "RainbowTitan", name: "Rainbow Titan", rarity: "Limited", biome: "Limited", income: 260, color: "#ff78c8", hint: "Weekly limited" },
	{ id: "CrownOrbit", name: "Crown Orbit", rarity: "Limited", biome: "Limited", income: 250, color: "#ffd250", hint: "Weekly limited" },
	{ id: "MythicNest", name: "Mythic Nest", rarity: "Limited", biome: "Limited", income: 230, color: "#78ffa0", hint: "Weekly limited" },
	{ id: "EclipseWyrm", name: "Eclipse Wyrm", rarity: "Limited", biome: "Limited", income: 280, color: "#28143c", hint: "Weekly limited" },
	{ id: "PrimeNest", name: "Prime Nest", rarity: "Apex", biome: "Prime", income: 320, color: "#ffdc50", hint: "Prime Egg only" },
	{ id: "SolarCrown", name: "Solar Crown", rarity: "Apex", biome: "Prime", income: 340, color: "#ffb428", hint: "Prime Egg only" },
	{ id: "VoidPrime", name: "Void Prime", rarity: "Apex", biome: "Prime", income: 360, color: "#5028a0", hint: "Prime Egg only" },
	{ id: "StormApex", name: "Storm Apex", rarity: "Apex", biome: "Prime", income: 350, color: "#5aa0ff", hint: "Prime Egg only" },
	{ id: "DawnPrime", name: "Dawn Prime", rarity: "Apex", biome: "Prime", income: 380, color: "#ffe68c", hint: "Prime Egg only" },
	{ id: "OrbitSovereign", name: "Orbit Sovereign", rarity: "Apex", biome: "Prime", income: 400, color: "#ffd246", hint: "Prime Egg only" },
];

export function petCount(): number {
	return pets.length;
}

